import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>MohitPhuldaliya</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="text-black">Home</main>
    </>
  );
}
